import type { Metadata } from "next";
import { Geist, Geist_Mono, Calistoga } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const calistoga = Calistoga({
	weight: "400",
	variable: "--font-calistoga",
  subsets: ['latin']
});

export const metadata: Metadata = {
	title: "To-Mo",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${calistoga.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
